name: Build Mod

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '-nobuild')" 
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Stop Gradle Daemons
      run: ./gradlew --stop

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: |
        ./gradlew --no-daemon build

    - name: List build directory
      run: ls -R build

    - name: Save build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/libs/*.jar
